# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pierre/Documents/project/libtestframework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pierre/Documents/project/libtestframework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pierre/Documents/project/libtestframework/CMakeFiles /home/pierre/Documents/project/libtestframework//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pierre/Documents/project/libtestframework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sqlite

# Build rule for target.
sqlite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sqlite
.PHONY : sqlite

# fast build rule for target.
sqlite/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite.dir/build.make CMakeFiles/sqlite.dir/build
.PHONY : sqlite/fast

#=============================================================================
# Target rules for targets named testframework

# Build rule for target.
testframework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testframework
.PHONY : testframework

# fast build rule for target.
testframework/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/build
.PHONY : testframework/fast

#=============================================================================
# Target rules for targets named testgenerator

# Build rule for target.
testgenerator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testgenerator
.PHONY : testgenerator

# fast build rule for target.
testgenerator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgenerator.dir/build.make CMakeFiles/testgenerator.dir/build
.PHONY : testgenerator/fast

#=============================================================================
# Target rules for targets named testdb

# Build rule for target.
testdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testdb
.PHONY : testdb

# fast build rule for target.
testdb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testdb.dir/build.make CMakeFiles/testdb.dir/build
.PHONY : testdb/fast

#=============================================================================
# Target rules for targets named gui

# Build rule for target.
gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gui
.PHONY : gui

# fast build rule for target.
gui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/build
.PHONY : gui/fast

Qt/Window/MainWindow.o: Qt/Window/MainWindow.cpp.o
.PHONY : Qt/Window/MainWindow.o

# target to build an object file
Qt/Window/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/Qt/Window/MainWindow.cpp.o
.PHONY : Qt/Window/MainWindow.cpp.o

Qt/Window/MainWindow.i: Qt/Window/MainWindow.cpp.i
.PHONY : Qt/Window/MainWindow.i

# target to preprocess a source file
Qt/Window/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/Qt/Window/MainWindow.cpp.i
.PHONY : Qt/Window/MainWindow.cpp.i

Qt/Window/MainWindow.s: Qt/Window/MainWindow.cpp.s
.PHONY : Qt/Window/MainWindow.s

# target to generate assembly for a file
Qt/Window/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/Qt/Window/MainWindow.cpp.s
.PHONY : Qt/Window/MainWindow.cpp.s

Qt/main.o: Qt/main.cpp.o
.PHONY : Qt/main.o

# target to build an object file
Qt/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/Qt/main.cpp.o
.PHONY : Qt/main.cpp.o

Qt/main.i: Qt/main.cpp.i
.PHONY : Qt/main.i

# target to preprocess a source file
Qt/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/Qt/main.cpp.i
.PHONY : Qt/main.cpp.i

Qt/main.s: Qt/main.cpp.s
.PHONY : Qt/main.s

# target to generate assembly for a file
Qt/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/Qt/main.cpp.s
.PHONY : Qt/main.cpp.s

lib/sqlite3/sqlite3.o: lib/sqlite3/sqlite3.c.o
.PHONY : lib/sqlite3/sqlite3.o

# target to build an object file
lib/sqlite3/sqlite3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite.dir/build.make CMakeFiles/sqlite.dir/lib/sqlite3/sqlite3.c.o
.PHONY : lib/sqlite3/sqlite3.c.o

lib/sqlite3/sqlite3.i: lib/sqlite3/sqlite3.c.i
.PHONY : lib/sqlite3/sqlite3.i

# target to preprocess a source file
lib/sqlite3/sqlite3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite.dir/build.make CMakeFiles/sqlite.dir/lib/sqlite3/sqlite3.c.i
.PHONY : lib/sqlite3/sqlite3.c.i

lib/sqlite3/sqlite3.s: lib/sqlite3/sqlite3.c.s
.PHONY : lib/sqlite3/sqlite3.s

# target to generate assembly for a file
lib/sqlite3/sqlite3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite.dir/build.make CMakeFiles/sqlite.dir/lib/sqlite3/sqlite3.c.s
.PHONY : lib/sqlite3/sqlite3.c.s

testframework/Database/Database.o: testframework/Database/Database.cpp.o
.PHONY : testframework/Database/Database.o

# target to build an object file
testframework/Database/Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/Database/Database.cpp.o
.PHONY : testframework/Database/Database.cpp.o

testframework/Database/Database.i: testframework/Database/Database.cpp.i
.PHONY : testframework/Database/Database.i

# target to preprocess a source file
testframework/Database/Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/Database/Database.cpp.i
.PHONY : testframework/Database/Database.cpp.i

testframework/Database/Database.s: testframework/Database/Database.cpp.s
.PHONY : testframework/Database/Database.s

# target to generate assembly for a file
testframework/Database/Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/Database/Database.cpp.s
.PHONY : testframework/Database/Database.cpp.s

testframework/Generator/Generator.o: testframework/Generator/Generator.cpp.o
.PHONY : testframework/Generator/Generator.o

# target to build an object file
testframework/Generator/Generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/Generator/Generator.cpp.o
.PHONY : testframework/Generator/Generator.cpp.o

testframework/Generator/Generator.i: testframework/Generator/Generator.cpp.i
.PHONY : testframework/Generator/Generator.i

# target to preprocess a source file
testframework/Generator/Generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/Generator/Generator.cpp.i
.PHONY : testframework/Generator/Generator.cpp.i

testframework/Generator/Generator.s: testframework/Generator/Generator.cpp.s
.PHONY : testframework/Generator/Generator.s

# target to generate assembly for a file
testframework/Generator/Generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/Generator/Generator.cpp.s
.PHONY : testframework/Generator/Generator.cpp.s

testframework/Generator/GeneratorArray.o: testframework/Generator/GeneratorArray.cpp.o
.PHONY : testframework/Generator/GeneratorArray.o

# target to build an object file
testframework/Generator/GeneratorArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/Generator/GeneratorArray.cpp.o
.PHONY : testframework/Generator/GeneratorArray.cpp.o

testframework/Generator/GeneratorArray.i: testframework/Generator/GeneratorArray.cpp.i
.PHONY : testframework/Generator/GeneratorArray.i

# target to preprocess a source file
testframework/Generator/GeneratorArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/Generator/GeneratorArray.cpp.i
.PHONY : testframework/Generator/GeneratorArray.cpp.i

testframework/Generator/GeneratorArray.s: testframework/Generator/GeneratorArray.cpp.s
.PHONY : testframework/Generator/GeneratorArray.s

# target to generate assembly for a file
testframework/Generator/GeneratorArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/Generator/GeneratorArray.cpp.s
.PHONY : testframework/Generator/GeneratorArray.cpp.s

testframework/testframework/TestFramework.o: testframework/testframework/TestFramework.cpp.o
.PHONY : testframework/testframework/TestFramework.o

# target to build an object file
testframework/testframework/TestFramework.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/testframework/TestFramework.cpp.o
.PHONY : testframework/testframework/TestFramework.cpp.o

testframework/testframework/TestFramework.i: testframework/testframework/TestFramework.cpp.i
.PHONY : testframework/testframework/TestFramework.i

# target to preprocess a source file
testframework/testframework/TestFramework.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/testframework/TestFramework.cpp.i
.PHONY : testframework/testframework/TestFramework.cpp.i

testframework/testframework/TestFramework.s: testframework/testframework/TestFramework.cpp.s
.PHONY : testframework/testframework/TestFramework.s

# target to generate assembly for a file
testframework/testframework/TestFramework.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testframework.dir/build.make CMakeFiles/testframework.dir/testframework/testframework/TestFramework.cpp.s
.PHONY : testframework/testframework/TestFramework.cpp.s

tests/database.o: tests/database.cpp.o
.PHONY : tests/database.o

# target to build an object file
tests/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testdb.dir/build.make CMakeFiles/testdb.dir/tests/database.cpp.o
.PHONY : tests/database.cpp.o

tests/database.i: tests/database.cpp.i
.PHONY : tests/database.i

# target to preprocess a source file
tests/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testdb.dir/build.make CMakeFiles/testdb.dir/tests/database.cpp.i
.PHONY : tests/database.cpp.i

tests/database.s: tests/database.cpp.s
.PHONY : tests/database.s

# target to generate assembly for a file
tests/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testdb.dir/build.make CMakeFiles/testdb.dir/tests/database.cpp.s
.PHONY : tests/database.cpp.s

tests/generator.o: tests/generator.cpp.o
.PHONY : tests/generator.o

# target to build an object file
tests/generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgenerator.dir/build.make CMakeFiles/testgenerator.dir/tests/generator.cpp.o
.PHONY : tests/generator.cpp.o

tests/generator.i: tests/generator.cpp.i
.PHONY : tests/generator.i

# target to preprocess a source file
tests/generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgenerator.dir/build.make CMakeFiles/testgenerator.dir/tests/generator.cpp.i
.PHONY : tests/generator.cpp.i

tests/generator.s: tests/generator.cpp.s
.PHONY : tests/generator.s

# target to generate assembly for a file
tests/generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testgenerator.dir/build.make CMakeFiles/testgenerator.dir/tests/generator.cpp.s
.PHONY : tests/generator.cpp.s

tests/gui.o: tests/gui.cpp.o
.PHONY : tests/gui.o

# target to build an object file
tests/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/tests/gui.cpp.o
.PHONY : tests/gui.cpp.o

tests/gui.i: tests/gui.cpp.i
.PHONY : tests/gui.i

# target to preprocess a source file
tests/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/tests/gui.cpp.i
.PHONY : tests/gui.cpp.i

tests/gui.s: tests/gui.cpp.s
.PHONY : tests/gui.s

# target to generate assembly for a file
tests/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/tests/gui.cpp.s
.PHONY : tests/gui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gui"
	@echo "... sqlite"
	@echo "... testdb"
	@echo "... testframework"
	@echo "... testgenerator"
	@echo "... Qt/Window/MainWindow.o"
	@echo "... Qt/Window/MainWindow.i"
	@echo "... Qt/Window/MainWindow.s"
	@echo "... Qt/main.o"
	@echo "... Qt/main.i"
	@echo "... Qt/main.s"
	@echo "... lib/sqlite3/sqlite3.o"
	@echo "... lib/sqlite3/sqlite3.i"
	@echo "... lib/sqlite3/sqlite3.s"
	@echo "... testframework/Database/Database.o"
	@echo "... testframework/Database/Database.i"
	@echo "... testframework/Database/Database.s"
	@echo "... testframework/Generator/Generator.o"
	@echo "... testframework/Generator/Generator.i"
	@echo "... testframework/Generator/Generator.s"
	@echo "... testframework/Generator/GeneratorArray.o"
	@echo "... testframework/Generator/GeneratorArray.i"
	@echo "... testframework/Generator/GeneratorArray.s"
	@echo "... testframework/testframework/TestFramework.o"
	@echo "... testframework/testframework/TestFramework.i"
	@echo "... testframework/testframework/TestFramework.s"
	@echo "... tests/database.o"
	@echo "... tests/database.i"
	@echo "... tests/database.s"
	@echo "... tests/generator.o"
	@echo "... tests/generator.i"
	@echo "... tests/generator.s"
	@echo "... tests/gui.o"
	@echo "... tests/gui.i"
	@echo "... tests/gui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

